// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ayMissouri",
            "url": "https://github.com/ayMissouri/watchlist-go.git"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/callback": {
            "get": {
                "description": "Where Discord sends the user back. Checks the CSRF state, issues a JWT, and bounces them to the frontend with it.",
                "tags": [
                    "auth"
                ],
                "summary": "OAuth2 callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth2 code from Discord",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF state token",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "get": {
                "description": "Redirects the user to Discord's OAuth2 login screen",
                "tags": [
                    "auth"
                ],
                "summary": "Discord OAuth2 login",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile of whoever the token belongs to.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Patches the current user's profile. Leave a field out and it stays as-is. Send an empty display name to clear it, in which case the username shows instead. ` + "`" + `settings` + "`" + ` is a free-form object (subtitle styling, that kind of thing) and gets shallow-merged into whatever is already stored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update current user",
                "parameters": [
                    {
                        "description": "Profile fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/calendar": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "What's coming up for this user: movies that aren't out yet and episodes that haven't aired, from shows on their watchlist. Soonest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calendar"
                ],
                "summary": "Get calendar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.CalendarResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/calendar/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rebuilds the calendar from the watchlist using fresh data from the meta service, then returns it. Handy right after adding something that hasn't come out yet.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calendar"
                ],
                "summary": "Refresh calendar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.CalendarResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/discover": {
            "get": {
                "description": "Returns one catalog. Use ` + "`" + `sort` + "`" + ` (optionally with ` + "`" + `genre` + "`" + `) for popular/top-rated, ` + "`" + `year` + "`" + ` for a single release year, or ` + "`" + `provider` + "`" + ` for a streaming service. If you send more than one, ` + "`" + `provider` + "`" + ` wins over ` + "`" + `year` + "`" + `, which wins over ` + "`" + `sort` + "`" + `. Cached for an hour.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discover"
                ],
                "summary": "Discover movies or shows",
                "parameters": [
                    {
                        "enum": [
                            "movie",
                            "series"
                        ],
                        "type": "string",
                        "description": "Media type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "popular",
                            "top_rated"
                        ],
                        "type": "string",
                        "description": "Sort order (default popular)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Genre filter, e.g. action, sci-fi (series also: reality-tv, talk-show, game-show)",
                        "name": "genre",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Release year, e.g. 2025 (overrides sort)",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "netflix",
                            "hbomax",
                            "disney",
                            "prime",
                            "appletv"
                        ],
                        "type": "string",
                        "description": "Streaming provider (overrides sort and year)",
                        "name": "provider",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/discover/all": {
            "get": {
                "description": "Popular movies, popular shows, top-rated movies and top-rated shows, all in one call. Cached for an hour.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discover"
                ],
                "summary": "Discover all catalogs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverAllResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The user's latest events, newest first. Meant for an activity feed, or just for showing people what we've recorded about them.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Recent activity",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Max events to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only include events at or after this Unix ms timestamp",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Only include events strictly before this Unix ms timestamp",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.EventsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Takes a batch of events from the client (play/pause, heartbeats, page views, that kind of thing) and appends them to the user's activity log. Anything with a blank or absurdly long type is dropped quietly.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Ingest activity events",
                "parameters": [
                    {
                        "description": "Batch of events",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.RecordEventsRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Quick liveness check. Also says whether the database is reachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/lobbies": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Opens a lobby with a shareable 6-character code. The body optionally seeds the video and playback state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "Create a watch-together lobby",
                "parameters": [
                    {
                        "description": "Initial state",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.UpdateLobbyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Lobby"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/lobbies/{code}/state": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Every member has the remote. Send only what changed such as ` + "`" + `playing` + "`" + `, ` + "`" + `position` + "`" + ` (seconds), or ` + "`" + `item_id` + "`" + ` with ` + "`" + `season` + "`" + `/` + "`" + `episode` + "`" + ` to switch video.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "Play, pause, seek, or switch video",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lobby code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "What changed",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.UpdateLobbyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Lobby"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/lobbies/{code}/stream": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Server-Sent Events. You are a member for as long as this connection is open.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "lobbies"
                ],
                "summary": "Join a lobby and follow its state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lobby code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "One ` + "`" + `state` + "`" + ` event per change",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Lobby"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/meta/movie/{id}": {
            "get": {
                "description": "Everything we know about a movie. Cached for a day.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Get movie details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID (e.g. tt0111161)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.MovieDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/meta/series/{id}": {
            "get": {
                "description": "Everything we know about a series, episodes included (they're in ` + "`" + `videos` + "`" + `). Cached for a day.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Get series details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID (e.g. tt3322312)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.SeriesDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the user's most recent notifications plus the unread count",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.NotificationsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications/read-all": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks every unread notification for the user as read",
                "tags": [
                    "notifications"
                ],
                "summary": "Mark all notifications read",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/notifications/{id}/read": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks a single notification as read",
                "tags": [
                    "notifications"
                ],
                "summary": "Mark a notification read",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Search by title. Leave ` + "`" + `type` + "`" + ` out and you get movies and shows mixed together, newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search movies and shows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "movie",
                            "series"
                        ],
                        "type": "string",
                        "description": "Filter by type",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "All-time numbers for the profile page: totals, watch time, top genres and top titles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Profile stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.ProfileStats"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats/wrapped": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Wrapped-style summary for one year: total watch time, counts, top genres/titles/decades, when you tend to watch (by month, hour and weekday), streaks, and whether you're a night owl. Current year if ` + "`" + `year` + "`" + ` is left out.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Year in review",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 2026,
                        "description": "Calendar year (UTC)",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WrappedStats"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/watchlist": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "The user's watchlist, one page at a time. Filter by type or status, sort however you like.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Get watchlist",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "tv",
                            "movie"
                        ],
                        "type": "string",
                        "description": "Filter by type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "watching",
                            "watched",
                            "plan_to_watch",
                            "paused",
                            "dropped"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "last_updated",
                            "title"
                        ],
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Sort order",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes several items in one go and tells you how many actually went.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Bulk delete watchlist items",
                "parameters": [
                    {
                        "description": "List of item IDs to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.BulkDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/watchlist/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single watchlist item by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Get watchlist item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID (e.g. t63174 or m533535)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistItem"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds the item, or replaces the whole thing if it's already there. Use the progress/status endpoints for partial updates.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Add or update watchlist item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID (e.g. t63174 or m533535)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Watchlist item",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistItem"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a watchlist item by ID",
                "tags": [
                    "watchlist"
                ],
                "summary": "Remove watchlist item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/watchlist/{id}/progress": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Just bumps playback progress. Everything else on the item stays as it was.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Update item progress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Progress update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.UpdateProgressRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/watchlist/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sets the watch status of an item (watching, watched, plan_to_watch, paused, dropped)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Update item status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.UpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_ayMissouri_watchlist-go_git_internal_models.BehaviorHints": {
            "type": "object",
            "properties": {
                "defaultVideoId": {
                    "type": "string"
                },
                "hasScheduledVideos": {
                    "type": "boolean"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.BulkDeleteRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.CalendarEntry": {
            "type": "object",
            "properties": {
                "episode": {
                    "type": "integer"
                },
                "episode_title": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imdb_id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "media_type": {
                    "description": "\"tv\" or \"movie\"",
                    "type": "string"
                },
                "poster_path": {
                    "type": "string"
                },
                "release_date": {
                    "type": "integer"
                },
                "released": {
                    "description": "Released is true once the release date has passed.",
                    "type": "boolean"
                },
                "season": {
                    "description": "Season/Episode are zero for movies.",
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.CalendarResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.CalendarEntry"
                    }
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.ClientEvent": {
            "type": "object",
            "properties": {
                "episode": {
                    "type": "integer"
                },
                "event_type": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "imdb_id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "occurred_at": {
                    "type": "integer"
                },
                "release_year": {
                    "type": "integer"
                },
                "runtime_minutes": {
                    "type": "integer"
                },
                "season": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverAllResponse": {
            "type": "object",
            "properties": {
                "popular_movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverItem"
                    }
                },
                "popular_shows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverItem"
                    }
                },
                "top_rated_movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverItem"
                    }
                },
                "top_rated_shows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverItem"
                    }
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverItem": {
            "type": "object",
            "properties": {
                "background": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "imdb_rating": {
                    "type": "string"
                },
                "poster": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverItem"
                    }
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.Episode": {
            "type": "object",
            "properties": {
                "episode": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "imdbRating": {
                    "type": "string"
                },
                "overview": {
                    "type": "string"
                },
                "released": {
                    "type": "string"
                },
                "season": {
                    "type": "integer"
                },
                "thumbnail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.EpisodeProgress": {
            "type": "object",
            "properties": {
                "episode": {
                    "type": "integer"
                },
                "last_updated": {
                    "type": "integer"
                },
                "progress": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Progress"
                },
                "season": {
                    "type": "integer"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.EventsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.UserEvent"
                    }
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.LabelCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.Link": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.Lobby": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "episode": {
                    "type": "integer"
                },
                "host": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "last_action": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LobbyAction"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LobbyMember"
                    }
                },
                "playing": {
                    "type": "boolean"
                },
                "position": {
                    "type": "number"
                },
                "season": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.LobbyAction": {
            "type": "object",
            "properties": {
                "at": {
                    "type": "integer"
                },
                "by": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LobbyMember"
                },
                "type": {
                    "description": "\"play\", \"pause\", \"seek\", or \"change\"",
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.LobbyMember": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.MovieDetail": {
            "type": "object",
            "properties": {
                "awards": {
                    "type": "string"
                },
                "background": {
                    "type": "string"
                },
                "behaviorHints": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.BehaviorHints"
                },
                "cast": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "country": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "director": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dvdRelease": {
                    "type": "string"
                },
                "genre": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "imdbRating": {
                    "type": "string"
                },
                "imdb_id": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Link"
                    }
                },
                "logo": {
                    "type": "string"
                },
                "moviedb_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "popularities": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Popularities"
                },
                "popularity": {
                    "type": "number"
                },
                "poster": {
                    "type": "string"
                },
                "releaseInfo": {
                    "type": "string"
                },
                "released": {
                    "type": "string"
                },
                "runtime": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "trailerStreams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.TrailerStream"
                    }
                },
                "trailers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Trailer"
                    }
                },
                "type": {
                    "type": "string"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Episode"
                    }
                },
                "writer": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.Notification": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "poster_path": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.NotificationsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Notification"
                    }
                },
                "unread": {
                    "type": "integer"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.Popularities": {
            "type": "object",
            "additionalProperties": {}
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.ProfileStats": {
            "type": "object",
            "properties": {
                "current_streak_days": {
                    "type": "integer"
                },
                "episodes_watched": {
                    "type": "integer"
                },
                "first_event_at": {
                    "type": "integer"
                },
                "items_added": {
                    "type": "integer"
                },
                "last_event_at": {
                    "type": "integer"
                },
                "longest_streak_days": {
                    "type": "integer"
                },
                "movies_watched": {
                    "type": "integer"
                },
                "shows_completed": {
                    "type": "integer"
                },
                "top_genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LabelCount"
                    }
                },
                "top_titles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LabelCount"
                    }
                },
                "total_events": {
                    "type": "integer"
                },
                "watch_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.Progress": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "number"
                },
                "watched": {
                    "type": "number"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.RecordEventsRequest": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.ClientEvent"
                    }
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.SearchResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.DiscoverItem"
                    }
                },
                "query": {
                    "type": "string"
                },
                "type": {
                    "description": "leave empty for mixed results",
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.SeriesDetail": {
            "type": "object",
            "properties": {
                "awards": {
                    "type": "string"
                },
                "background": {
                    "type": "string"
                },
                "behaviorHints": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.BehaviorHints"
                },
                "cast": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "country": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "director": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dvdRelease": {
                    "type": "string"
                },
                "genre": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "imdbRating": {
                    "type": "string"
                },
                "imdb_id": {
                    "type": "string"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Link"
                    }
                },
                "logo": {
                    "type": "string"
                },
                "moviedb_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "popularities": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Popularities"
                },
                "popularity": {
                    "type": "number"
                },
                "poster": {
                    "type": "string"
                },
                "releaseInfo": {
                    "type": "string"
                },
                "released": {
                    "type": "string"
                },
                "runtime": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "trailerStreams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.TrailerStream"
                    }
                },
                "trailers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Trailer"
                    }
                },
                "tvdb_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Episode"
                    }
                },
                "writer": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.ShowProgress": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.EpisodeProgress"
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.Trailer": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.TrailerStream": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "ytId": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.UpdateLobbyRequest": {
            "type": "object",
            "properties": {
                "episode": {
                    "type": "integer"
                },
                "item_id": {
                    "type": "string"
                },
                "playing": {
                    "type": "boolean"
                },
                "position": {
                    "type": "number"
                },
                "season": {
                    "type": "integer"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.UpdateProgressRequest": {
            "type": "object",
            "properties": {
                "episodes_total": {
                    "type": "integer"
                },
                "episodes_watched": {
                    "type": "integer"
                },
                "last_episode_watched": {
                    "type": "integer"
                },
                "last_season_watched": {
                    "type": "integer"
                },
                "last_updated": {
                    "type": "integer"
                },
                "progress": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Progress"
                },
                "show_progress": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.ShowProgress"
                },
                "status": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistStatus"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.UpdateStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistStatus"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "settings": {
                    "type": "object"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "display_name": {
                    "type": "string"
                },
                "has_access": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "settings": {
                    "type": "object"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.UserEvent": {
            "type": "object",
            "properties": {
                "episode": {
                    "type": "integer"
                },
                "event_type": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "imdb_id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "media_type": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "occurred_at": {
                    "type": "integer"
                },
                "release_year": {
                    "type": "integer"
                },
                "runtime_minutes": {
                    "type": "integer"
                },
                "season": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.WatchRef": {
            "type": "object",
            "properties": {
                "item_id": {
                    "type": "string"
                },
                "occurred_at": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistItem": {
            "type": "object",
            "properties": {
                "backdrop_path": {
                    "type": "string"
                },
                "episodes_total": {
                    "type": "integer"
                },
                "episodes_watched": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "imdb_id": {
                    "type": "string"
                },
                "last_episode_watched": {
                    "type": "integer"
                },
                "last_season_watched": {
                    "description": "Pointers so \"never set\" is distinguishable from season/episode 0.",
                    "type": "integer"
                },
                "last_updated": {
                    "type": "integer"
                },
                "poster_path": {
                    "type": "string"
                },
                "progress": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.Progress"
                },
                "show_progress": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.ShowProgress"
                },
                "status": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistStatus"
                },
                "title": {
                    "type": "string"
                },
                "tmdb_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistItem"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.PaginationMeta"
                }
            }
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.WatchlistStatus": {
            "type": "string",
            "enum": [
                "watching",
                "watched",
                "plan_to_watch",
                "paused",
                "dropped"
            ],
            "x-enum-varnames": [
                "StatusWatching",
                "StatusWatched",
                "StatusPlanToWatch",
                "StatusPaused",
                "StatusDropped"
            ]
        },
        "github_com_ayMissouri_watchlist-go_git_internal_models.WrappedStats": {
            "type": "object",
            "properties": {
                "app_opens": {
                    "type": "integer"
                },
                "busiest_month": {
                    "type": "string"
                },
                "decades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LabelCount"
                    }
                },
                "episodes_watched": {
                    "type": "integer"
                },
                "first_watch": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchRef"
                },
                "items_added": {
                    "type": "integer"
                },
                "last_watch": {
                    "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.WatchRef"
                },
                "longest_streak_days": {
                    "type": "integer"
                },
                "movies_watched": {
                    "type": "integer"
                },
                "night_owl": {
                    "type": "boolean"
                },
                "peak_hour": {
                    "type": "integer"
                },
                "searches": {
                    "type": "integer"
                },
                "shows_completed": {
                    "type": "integer"
                },
                "shows_started": {
                    "type": "integer"
                },
                "top_genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LabelCount"
                    }
                },
                "top_titles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_ayMissouri_watchlist-go_git_internal_models.LabelCount"
                    }
                },
                "unique_titles": {
                    "type": "integer"
                },
                "watch_time_minutes": {
                    "type": "integer"
                },
                "watches_by_hour": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "watches_by_month": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "watches_by_weekday": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "internal_handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your JWT token as: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Watchlist API",
	Description:      "Backend API for tracking movies and TV shows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
